# Generated by Django 4.2.17 on 2025-01-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'requested'), (1, 'confirmed')], default=0)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patron_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
