# Generated by Django 4.2.17 on 2025-01-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='patron',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
