# Generated by Django 4.2.17 on 2025-01-12 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_rename_content_reservation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'requested'), (1, 'confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
