# Generated by Django 4.2.17 on 2025-05-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0008_alter_feedback_patron_alter_feedback_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(max_length=75),
        ),
    ]
