# Generated by Django 4.2.17 on 2025-05-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
